Repository datavisyn/tdp_core, pull requests merged in 2019-12, with the labels that each got.

#260 Update template files and dependencies
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .yo-rc.json
  ISSUE_TEMPLATE.md
  buildInfo.js
  package-lock.json
  package.json
  requirements.txt
  setup.py
  webpack.config.js
Labels: release: major, type: technical debt

#261 Switch to phovea_clue@develop
  package-lock.json
  package.json
Labels: type: technical debt

#262 Fix compatibility issues with lineup v4 alpha12
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .yo-rc.json
  ISSUE_TEMPLATE.md
  buildInfo.js
  package-lock.json
  package.json
  requirements.txt
  setup.py
  src/lineup/ARankingView.ts
  src/lineup/desc.ts
  src/lineup/internal/LineUpPanelActions.ts
  src/lineup/internal/OverviewColumn.ts
  src/lineup/internal/cmds.ts
  src/lineup/internal/column.ts
  src/lineup/internal/export.ts
  webpack.config.js
Labels: type: refactor

#269 Added group property to score loader extension desc
  src/extensions.ts
  src/lineup/internal/LineUpPanelActions.ts
Labels: release: patch

#267 Added lazy loaded column interface to functions like addLazyColu…
  src/base/AEmbeddedRanking.ts
  src/lineup/ARankingView.ts
  src/lineup/internal/column.ts
Labels: release: patch

#264 Move IResult, ISearchProvider and ISearchProviderDesc from dTiles to tdp_core
  src/public/search/SearchProviderInterfaces.ts
  src/public/search/index.ts
Labels: release: minor, type: refactor

#256 Add I18N support and extract language strings
  package-lock.json
  package.json
  src/ATDPApplication.ts
  src/SessionList.ts
  src/assets/locales/en/tdp.json
  src/base/ViewWrapper.ts
  src/dialogs.ts
  src/form/elements/FormMap.ts
  src/internal/EditProvenanceGraphMenu.ts
  src/internal/cmds.ts
  src/internal/utils.ts
  src/lineup/AOverviewDetailRankingView.ts
  src/lineup/ARankingView.ts
  src/lineup/internal/LineUpPanelActions.ts
  src/lineup/internal/OverviewColumn.ts
  src/lineup/internal/cmds.ts
  src/lineup/internal/export.ts
  src/lineup/internal/scorecmds.ts
  src/notifications.ts
  src/phovea.ts
  src/storage/NamedSetList.ts
  src/storage/editDialog.ts
  src/tour/TourManager.ts
  src/views/ATableView.ts
  src/views/AView.ts
  src/views/ChooserProxyView.ts
  src/views/CompositeView.ts
  src/views/ProxyView.ts
  src/views/SelectionChooser.ts
  src/views/messaging/MessagingProxyView.ts
  tsconfig.json
Labels: release: minor, type: feature
