Repository datavisyn/tdp_core, pull requests merged in 2019-11, with the labels that each got.

#235 Comments for ARankingView
  src/extensions.ts
  src/lineup/ARankingView.ts
Labels: type: docu

#248 Use LineUp v3 develop branch in tdp_core develop
  package.json
Labels: type: feature

#252 Release 6.1.0
  package-lock.json
  package.json
  src/ATDPApplication.ts
  src/SessionList.ts
  src/dialogs.ts
  src/extensions.ts
  src/lineup/ARankingView.ts
  src/lineup/internal/LineUpPanelActions.ts
  src/lineup/internal/export.ts
Labels: release: minor
