Repository datavisyn/tdp_core, pull requests merged in 2019-09, with the labels that each got.

#211 Update to LineUp v3.2 and adapt to changes
  package.json
  src/lineup/ARankingView.ts
  src/lineup/internal/LineUpColors.ts
Labels: type: refactor

#185 Allow custom form elements with extension point `epTdpCoreFormElement`
  src/extensions.ts
  src/form/FormBuilder.ts
  src/form/FormDialog.ts
  src/form/elements/AFormElement.ts
  src/form/elements/Form.ts
  src/form/elements/FormButton.ts
  src/form/elements/FormCheckBox.ts
  src/form/elements/FormInputText.ts
  src/form/elements/FormMap.ts
  src/form/elements/FormRadio.ts
  src/form/elements/FormSelect.ts
  src/form/elements/FormSelect2.ts
  src/form/elements/FormSelect3.ts
  src/form/elements/Select3.ts
  src/form/elements/builder.ts
  src/form/elements/index.ts
  src/form/index.ts
  src/form/interfaces.ts
  src/form/internal/Select3.ts
  src/form/internal/index.ts
  src/lineup/ARankingView.ts
  src/phovea.ts
  src/views/AView.ts
  src/views/ProxyView.ts
  tests/select3.test.ts
Labels: type: feature, type: refactor

#177 Add less and greater filters to DB views
  src/rest.ts
  tdp_core/db.py
  tdp_core/sql_filter.py
Labels: type: feature

#220 Add help text to "Save List of Entities" dialog
  src/storage/editDialog.ts
Labels: type: feature
