Repository datavisyn/tdp_core, pull requests merged in 2020-08, with the labels that each got.

#411 Fix provenance replay of LineUp actions
  dist/lineup/internal/cmds.d.ts
  dist/lineup/internal/cmds.js
  dist/lineup/internal/cmds.js.map
  src/lineup/internal/cmds.ts
Labels: priority: high, release: patch, type: bug

#413 Handle Uint8Array, Uint16Array, and Uint32Array of ordered indicies from LineUp `getOrder()`
  dist/lineup/ARankingView.js
  dist/lineup/ARankingView.js.map
  dist/lineup/internal/ExportUtils.js
  dist/lineup/internal/ExportUtils.js.map
  dist/lineup/internal/LineUpPanelActions.js
  dist/lineup/internal/LineUpPanelActions.js.map
  src/lineup/ARankingView.ts
  src/lineup/internal/ExportUtils.ts
  src/lineup/internal/LineUpPanelActions.ts
Labels: release: minor, type: bug

#414 Release 10.0.1
  dist/ATDPApplication.d.ts
  dist/ATDPApplication.js
  dist/ATDPApplication.js.map
  dist/lineup/ARankingView.js
  dist/lineup/ARankingView.js.map
  dist/lineup/internal/ExportUtils.js
  dist/lineup/internal/ExportUtils.js.map
  dist/lineup/internal/LineUpPanelActions.js
  dist/lineup/internal/LineUpPanelActions.js.map
  dist/lineup/internal/cmds.d.ts
  dist/lineup/internal/cmds.js
  dist/lineup/internal/cmds.js.map
  package.json
  src/ATDPApplication.ts
  src/lineup/ARankingView.ts
  src/lineup/internal/ExportUtils.ts
  src/lineup/internal/LineUpPanelActions.ts
  src/lineup/internal/cmds.ts
Labels: release: patch
