Repository datavisyn/tdp_core, pull requests merged in 2020-03, with the labels that each got.

#308 Update to Typescript 3.8
  package.json
  src/extensions.ts
  src/form/elements/FormSelect.ts
  src/form/elements/FormSelect2.ts
  src/form/elements/FormSelect3.ts
  src/internal/utils.ts
  tsconfig.json
Labels: priority: high, release: major, type: refactor

#315 Update dependencies and requirements
  package.json
  requirements.txt
  requirements_dev.txt
  tdp_core/utils.py
Labels: dependencies, priority: medium, type: refactor

#319 Refactor PanelTab extension point
  src/extensions.ts
  src/lineup/internal/LineUpPanelActions.ts
  src/lineup/internal/panel/PanelTab.ts
Labels: release: minor, type: refactor

#285 Create extension point to connect the touring panel/Refactor LineupSidePanel
  src/assets/locales/en/tdp.json
  src/extensions.ts
  src/lineup/internal/LineUpPanelActions.ts
  src/lineup/internal/panel/PanelAddColumnButton.ts
  src/lineup/internal/panel/PanelButton.ts
  src/lineup/internal/panel/PanelDownloadButton.ts
  src/lineup/internal/panel/PanelHeader.ts
  src/lineup/internal/panel/PanelRankingButton.ts
  src/lineup/internal/panel/PanelTab.ts
  src/lineup/internal/panel/PanelTabContainer.ts
  src/lineup/internal/panel/SearchBoxProvider.ts
  src/lineup/internal/utils.ts
  src/styles/_view_lineup.scss
Labels: release: minor, type: refactor

#317 Change `buildId` to `JSON.stringify(buildId)`
  webpack.config.js
Labels: priority: medium, type: refactor

#321 Remove `overflow: hidden` to fix download drop down
  src/styles/_view_lineup.scss
Labels: release: patch, type: bug

#322 Release 9.0.0
  .github/CODEOWNERS
  package.json
  requirements.txt
  requirements_dev.txt
  src/assets/locales/en/tdp.json
  src/extensions.ts
  src/form/elements/FormSelect.ts
  src/form/elements/FormSelect2.ts
  src/form/elements/FormSelect3.ts
  src/form/elements/Select3.ts
  src/internal/utils.ts
  src/lineup/ARankingView.ts
  src/lineup/internal/LineUpPanelActions.ts
  src/lineup/internal/cmds.ts
  src/lineup/internal/panel/PanelAddColumnButton.ts
  src/lineup/internal/panel/PanelButton.ts
  src/lineup/internal/panel/PanelDownloadButton.ts
  src/lineup/internal/panel/PanelHeader.ts
  src/lineup/internal/panel/PanelRankingButton.ts
  src/lineup/internal/panel/PanelTab.ts
  src/lineup/internal/panel/PanelTabContainer.ts
  src/lineup/internal/panel/SearchBoxProvider.ts
  src/lineup/internal/utils.ts
  src/notifications.ts
  src/styles/_view_lineup.scss
  tdp_core/utils.py
  tdp_core/xlsx.py
  tsconfig.json
  webpack.config.js
Labels: release: major

#326 Make repository public
  package.json
Labels: release: major, type: refactor

#328 Fix lint errors
  tsd.d.ts
Labels: release: patch, type: bug

#329 Release 9.1.0
  package.json
  tsd.d.ts
Labels: release: minor

#299 Migrate to jest for testing
  .circleci/config.yml
  jest.config.js
  karma.conf.js
  package.json
  src/SessionList.ts
  src/form/elements/FormMap.ts
  src/form/elements/FormSelect2.ts
  src/form/elements/Select3.ts
  tests/cached.test.ts
  tests/select3.test.ts
  tsd.d.ts
  webpack.config.js
Labels: release: major, type: refactor
