Repository datavisyn/tdp_core, pull requests merged in 2020-04, with the labels that each got.

#350 Use pinned ts-jest version
  package.json
Labels: priority: high, type: bug

#348 Set OverviewColumn renderer directly in column description
  src/lineup/internal/OverviewColumn.ts
Labels: release: patch

#351 Ignore live preview events
  package.json
  src/lineup/ARankingView.ts
  src/lineup/internal/cmds.ts
  src/styles/_view_lineup.scss
Labels: release: minor, type: refactor

#358 Fix LineUp CMD bug
  src/lineup/internal/cmds.ts
Labels: release: minor, type: bug

#356 Change the overflow of the SidePanel to be compatible with lineup-v4
  src/styles/_view_lineup.scss
Labels: release: minor, type: bug

#360 Fix typos in locale file
  src/assets/locales/en/tdp.json
Labels: release: patch
