Repository datavisyn/tdp_core, pull requests merged in 2020-10, with the labels that each got.

#428 Add option in ATDPApplication to hide the provenance menu (aka `Session Analysis Management`)
  dist/ATDPApplication.d.ts
  dist/ATDPApplication.js
  dist/ATDPApplication.js.map
  src/ATDPApplication.ts
Labels: release: minor, type: feature

#431 Set missing default value for `showProvenanceMenu` (amendment for PR #428)
  dist/ATDPApplication.d.ts
  dist/ATDPApplication.js
  dist/ATDPApplication.js.map
  src/ATDPApplication.ts
Labels: release: patch

#423 Change Persist Session to Save Session & Persist to Save
  dist/locales/en/tdp.json
  dist/utils/ProvenanceGraphMenuUtils.js
  dist/utils/ProvenanceGraphMenuUtils.js.map
  dist/utils/SessionList.js
  dist/utils/SessionList.js.map
  src/locales/en/tdp.json
  src/utils/ProvenanceGraphMenuUtils.ts
  src/utils/SessionList.ts
Labels: release: minor, type: refactor

#425 Hide open button in Open Existing Session Dialog
  dist/locales/en/tdp.json
  dist/scss/_dialogs.scss
  dist/utils/EditProvenanceGraphMenu.js
  dist/utils/EditProvenanceGraphMenu.js.map
  src/locales/en/tdp.json
  src/scss/_dialogs.scss
  src/utils/EditProvenanceGraphMenu.ts
Labels: release: minor, type: refactor

#426 Improve locale strings for better UX
  dist/locales/en/tdp.json
  src/locales/en/tdp.json
Labels: release: minor, type: refactor

#435 Adding the column summary to the exported column header
  dist/lineup/internal/ExportUtils.js
  dist/lineup/internal/ExportUtils.js.map
  src/lineup/internal/ExportUtils.ts
Labels: release: minor

#433 Refactor the add grouped column dialog to support multiple columns
  dist/lineup/internal/LineUpPanelActions.js
  dist/lineup/internal/LineUpPanelActions.js.map
  dist/locales/en/tdp.json
  src/lineup/internal/LineUpPanelActions.ts
  src/locales/en/tdp.json
Labels: release: minor, type: feature

#424 Change Edit Session dialog's button name
  dist/locales/en/tdp.json
  dist/utils/ProvenanceGraphMenuUtils.js
  dist/utils/ProvenanceGraphMenuUtils.js.map
  dist/utils/SessionList.js
  src/locales/en/tdp.json
  src/utils/ProvenanceGraphMenuUtils.ts
  src/utils/SessionList.ts
Labels: release: minor, type: refactor

#436 Change persisted sessions to saved sessions and all related labels
  dist/locales/en/tdp.json
  dist/utils/EditProvenanceGraphMenu.js
  dist/utils/EditProvenanceGraphMenu.js.map
  dist/utils/ProvenanceGraphMenuUtils.js
  dist/utils/ProvenanceGraphMenuUtils.js.map
  src/locales/en/tdp.json
  src/utils/EditProvenanceGraphMenu.ts
  src/utils/ProvenanceGraphMenuUtils.ts
Labels: release: minor, type: refactor

#437 Wait for correct LineUp event for aggregation provenance action
  dist/lineup/internal/cmds.d.ts
  dist/lineup/internal/cmds.js
  dist/lineup/internal/cmds.js.map
  src/lineup/internal/cmds.ts
Labels: release: patch, type: bug
