Repository datavisyn/tdp_core, pull requests merged in 2020-01, with the labels that each got.

#270 Migrate to Python 3.7
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  requirements.txt
  requirements_dev.txt
  setup.py
  tdp_core/__init__.py
  tdp_core/bytes_to_string_encoder.py
  tdp_core/config.py
  tdp_core/db.py
  tdp_core/dbview.py
  tdp_core/formatter.py
  tdp_core/mapping_table.py
  tdp_core/sql_filter.py
  tdp_core/swagger.py
  tdp_core/utils.py
  tdp_core/xlsx.py
  tox.ini
Labels: release: major, type: refactor

#284 Make DB timeout message more explicit
  src/assets/locales/en/tdp.json
  src/notifications.ts
  tdp_core/db.py
Labels: release: minor, type: feature

#289 Release 8.0.0
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .travis.yml
  package-lock.json
  package.json
  requirements.txt
  requirements_dev.txt
  setup.py
  src/assets/locales/en/tdp.json
  src/base/AEmbeddedRanking.ts
  src/notifications.ts
  tdp_core/__init__.py
  tdp_core/bytes_to_string_encoder.py
  tdp_core/config.py
  tdp_core/db.py
  tdp_core/dbview.py
  tdp_core/formatter.py
  tdp_core/mapping_table.py
  tdp_core/sql.py
  tdp_core/sql_filter.py
  tdp_core/swagger.py
  tdp_core/utils.py
  tdp_core/xlsx.py
  tox.ini
  tsconfig_dev.json
  tslint.json
  webpack.config.js
Labels: release: major
