Repository datavisyn/tdp_core, pull requests merged in 2020-07, with the labels that each got.

#385 Track in provenance graph the`groupingChanged` LineUp event
  src/lineup/internal/cmds.ts
  src/lineup/internal/cmds/filter.ts
  tests/lineup/internal/cmds/filter.test.ts
Labels: release: minor, type: feature

#388 Add missing spaces in tdp locale
  src/assets/locales/en/tdp.json
Labels: release: patch, type: bug

#353 Derive set column categories automatically
  tdp_core/db.py
Labels: release: minor, type: feature

#391 Fix numbers as text in Excel download
  tdp_core/xlsx.py
Labels: priority: medium, type: bug

#393 ProxyView: Entity selection and external link swapped
  src/views/ChooserProxyView.ts
  src/views/ProxyView.ts
Labels: release: patch, type: bug

#395 RankingView: Increase z-index of overview button on hover
  src/styles/_view_lineup.scss
Labels: release: patch, type: bug

#398 Improve tour documentation and add `doubleClick` and `submitForm` helper
  src/tour/Tour.ts
  src/tour/extensions.ts
  src/tour/scripter.ts
Labels: release: minor, type: feature, type: refactor

#402 Changed CSS selector for main LineUp ranking
  dist/scss/_view_lineup.scss
  src/scss/_view_lineup.scss
Labels: release: patch, type: bug

#403 Merge the two different versions of _view_lineup.scss
  dist/scss/_view_lineup.scss
  src/scss/_view_lineup.scss
Labels: type: bug

#405 Fix position of the overview warning message
  dist/scss/_view_lineup.scss
  src/scss/_view_lineup.scss
Labels: release: patch, type: bug
