Repository datavisyn/tdp_core, pull requests merged in 2021-11, with the labels that each got.

#573 Fix missing closing tag in persisitent session tab
  dist/utils/SessionList.js
  dist/utils/SessionList.js.map
  src/utils/SessionList.ts
Labels: type: bug, release: patch

#588 Made redis mostly optional
  tdp_core/__init__.py
  tdp_core/assigner.py
  tdp_core/cache.py
  tdp_core/config.json
  tdp_core/redis_mapping_table.py
  tdp_core/utils.py
Labels: release: major

#586 Fix Select2 clear all button style + top align FormMap items
  dist/form/elements/FormMap.js
  dist/form/elements/FormMap.js.map
  dist/scss/vendors/_select2.scss
  src/form/elements/FormMap.ts
  src/scss/vendors/_select2.scss
Labels: type: bug
