Repository datavisyn/tdp_core, pull requests merged in 2021-01, with the labels that each got.

#463 Set default file format to `xlsx` in the customize download dialog
  dist/lineup/internal/panel/PanelDownloadButton.js
  dist/lineup/internal/panel/PanelDownloadButton.js.map
  src/lineup/internal/panel/PanelDownloadButton.ts
Labels: type: feature

#464 Fix overlapping add column drop down
  dist/lineup/internal/panel/PanelAddColumnButton.js
  dist/lineup/internal/panel/PanelAddColumnButton.js.map
  dist/lineup/internal/panel/PanelDownloadButton.js
  dist/lineup/internal/panel/PanelDownloadButton.js.map
  dist/lineup/internal/panel/PanelSaveNamedSetButton.js
  dist/lineup/internal/panel/PanelSaveNamedSetButton.js.map
  src/lineup/internal/panel/PanelAddColumnButton.ts
  src/lineup/internal/panel/PanelDownloadButton.ts
  src/lineup/internal/panel/PanelSaveNamedSetButton.ts
Labels: release: patch, type: bug

#465 Update name set dialog title based on selection
  dist/lineup/internal/panel/PanelSaveNamedSetButton.js
  dist/lineup/internal/panel/PanelSaveNamedSetButton.js.map
  dist/locales/en/tdp.json
  dist/storage/NamedSetList.js
  dist/storage/NamedSetList.js.map
  dist/storage/StoreUtils.d.ts
  dist/storage/StoreUtils.js
  dist/storage/StoreUtils.js.map
  src/lineup/internal/panel/PanelSaveNamedSetButton.ts
  src/locales/en/tdp.json
  src/storage/NamedSetList.ts
  src/storage/StoreUtils.ts
Labels: release: minor, type: feature

#466 Add error handling + slight design update of custom download dialog
  dist/lineup/internal/panel/PanelDownloadButton.js
  dist/lineup/internal/panel/PanelDownloadButton.js.map
  dist/locales/en/tdp.json
  dist/scss/components/_view_lineup.scss
  src/lineup/internal/panel/PanelDownloadButton.ts
  src/locales/en/tdp.json
  src/scss/components/_view_lineup.scss
Labels: release: minor, type: feature

#467 Use datavisyn loading icon with datavisyn theme
  dist/assets/icons/datavisyn_loading.gif
  dist/scss/_datavisyn.scss
  dist/scss/abstracts/_variables.scss
  src/assets/icons/datavisyn_loading.gif
  src/scss/_datavisyn.scss
  src/scss/abstracts/_variables.scss
Labels: release: minor, type: feature

#476 Fix arrow direction of Ordino sidebar (un-)collapse button
  dist/scss/components/_view_lineup.scss
  src/scss/components/_view_lineup.scss
Labels: release: patch
