Repository datavisyn/tdp_core, pull requests merged in 2021-12, with the labels that each got.

#592 Fixed tour backdrop blocker
  dist/scss/components/_tour.scss
  dist/tour/TourManager.js
  dist/tour/TourManager.js.map
  src/scss/components/_tour.scss
  src/tour/TourManager.ts
Labels: release: patch

#594 Add compressor to remove consecutive nodes
  dist/base/Compression.d.ts
  dist/base/Compression.js
  dist/base/Compression.js.map
  dist/base/Selection.js
  dist/base/Selection.js.map
  dist/utils/TDPApplicationUtils.js
  dist/utils/TDPApplicationUtils.js.map
  src/base/Compression.ts
  src/base/Selection.ts
  src/utils/TDPApplicationUtils.ts
  tests/base/Compression.test.ts
Labels: type: bug

#601 Add `readonly` and `disabled` options to Select3
  dist/form/elements/Select3.d.ts
  dist/form/elements/Select3.js
  dist/form/elements/Select3.js.map
  dist/scss/vendors/_select2.scss
  src/form/elements/Select3.ts
  src/scss/vendors/_select2.scss
Labels: type: feature
