Repository datavisyn/tdp_core, pull requests merged in 2022-10, with the labels that each got.

#793 deps: Update dependency lineupjs@4.7.0
  package.json
Labels: dependencies, type: technical debt, release: minor

#788 feat: Added engine parameter to onBuiltLineUp in Ranking.tsx
  dist/lineup/Ranking.d.ts
  dist/lineup/Ranking.d.ts.map
  dist/lineup/Ranking.js
  dist/lineup/Ranking.js.map
  dist/lineup/panel/PanelButton.d.ts
  dist/lineup/panel/PanelButton.d.ts.map
  dist/lineup/panel/PanelButton.js
  dist/lineup/panel/PanelButton.js.map
  dist/lineup/structureImage/StructureImageFilterDialog.js
  dist/lineup/structureImage/StructureImageFilterDialog.js.map
  src/lineup/Ranking.tsx
  src/lineup/panel/PanelButton.ts
  src/lineup/structureImage/StructureImageFilterDialog.ts
Labels: type: feature, release: patch

#799 feat: Add `removePlugins` method to plugin registry
  dist/app/PluginRegistry.d.ts
  dist/app/PluginRegistry.d.ts.map
  dist/app/PluginRegistry.js
  dist/app/PluginRegistry.js.map
  src/app/PluginRegistry.ts
Labels: type: feature, release: minor

#801 fix: Avoid `AttachmentUtils` calls when Reprovisyn feature flag is enabled
  dist/lineup/ARankingView.d.ts.map
  dist/lineup/ARankingView.js
  dist/lineup/ARankingView.js.map
  dist/lineup/Ranking.d.ts.map
  dist/lineup/Ranking.js
  dist/lineup/Ranking.js.map
  dist/lineup/internal/ScoreUtils.d.ts.map
  dist/lineup/internal/ScoreUtils.js
  dist/lineup/internal/ScoreUtils.js.map
  src/lineup/ARankingView.ts
  src/lineup/Ranking.tsx
  src/lineup/internal/ScoreUtils.ts
Labels: type: refactor, type: technical debt, release: minor

#803 Add caching of users in the current request
  .gitignore
  README.md
  tdp_core/security/manager.py
Labels: type: bug, release: patch
