Repository datavisyn/tdp_core, pull requests merged in 2022-04, with the labels that each got.

#681 Fix side effects in `isSameSelection` function
  dist/views/ViewUtils.d.ts.map
  dist/views/ViewUtils.js
  dist/views/ViewUtils.js.map
  src/views/ViewUtils.ts
Labels: type: bug, release: patch

#691 Add showInContext option to ARankingView
  dist/lineup/ARankingView.d.ts.map
  dist/lineup/ARankingView.js
  dist/lineup/ARankingView.js.map
  dist/lineup/IARankingViewOptions.d.ts
  dist/lineup/IARankingViewOptions.d.ts.map
  src/lineup/ARankingView.ts
  src/lineup/IARankingViewOptions.ts
Labels: type: feature, release: minor

#689 Bar Chart Improvements
  dist/locales/en/tdp.json
  dist/vis/LineupVisWrapper.d.ts
  dist/vis/LineupVisWrapper.d.ts.map
  dist/vis/LineupVisWrapper.js
  dist/vis/LineupVisWrapper.js.map
  dist/vis/Vis.js
  dist/vis/Vis.js.map
  dist/vis/bar/BarVisSidebar.d.ts.map
  dist/vis/bar/BarVisSidebar.js
  dist/vis/bar/BarVisSidebar.js.map
  dist/vis/bar/utils.d.ts.map
  dist/vis/bar/utils.js
  dist/vis/bar/utils.js.map
  dist/vis/general/layoutUtils.d.ts
  dist/vis/general/layoutUtils.d.ts.map
  dist/vis/general/layoutUtils.js
  dist/vis/general/layoutUtils.js.map
  dist/vis/interfaces.d.ts
  dist/vis/interfaces.d.ts.map
  dist/vis/scatter/ScatterVis.js
  dist/vis/scatter/ScatterVis.js.map
  dist/vis/sidebar/BarDirectionButtons.d.ts.map
  dist/vis/sidebar/BarDirectionButtons.js
  dist/vis/sidebar/BarDirectionButtons.js.map
  dist/vis/sidebar/GroupSelect.d.ts
  dist/vis/sidebar/GroupSelect.d.ts.map
  dist/vis/sidebar/GroupSelect.js
  dist/vis/sidebar/GroupSelect.js.map
  src/locales/en/tdp.json
  src/vis/LineupVisWrapper.ts
  src/vis/Vis.tsx
  src/vis/bar/BarVisSidebar.tsx
  src/vis/bar/utils.ts
  src/vis/general/layoutUtils.ts
  src/vis/interfaces.ts
  src/vis/layoutUtils.ts
  src/vis/scatter/ScatterVis.tsx
  src/vis/sidebar/BarDirectionButtons.tsx
  src/vis/sidebar/GroupSelect.tsx
Labels: type: feature, type: refactor, release: minor, package: vis

#679 Rename `dataDesc` to `columnDesc` in `VisynDataViewPluginType`
  dist/base/rest.d.ts
  dist/lineup/internal/ScoreUtils.d.ts
  dist/lineup/internal/ScoreUtils.d.ts.map
  dist/utils/TDPApplicationUtils.d.ts
  dist/utils/TDPApplicationUtils.d.ts.map
  dist/views/scatterplot/base/AScatterplot.d.ts
  dist/views/visyn/interfaces.d.ts
  dist/views/visyn/interfaces.d.ts.map
  dist/vis/Vis.js
  dist/vis/Vis.js.map
  dist/vis/bar/utils.d.ts.map
  dist/vis/bar/utils.js
  dist/vis/bar/utils.js.map
  dist/vis/sidebar/utils.d.ts
  dist/vis/sidebar/utils.d.ts.map
  src/views/visyn/interfaces.ts
Labels: type: refactor

#693 Extract client config typings to interface
  dist/ATDPApplication.d.ts
  dist/ATDPApplication.d.ts.map
  dist/base/rest.d.ts
  dist/components/dialogs.d.ts
  dist/components/dialogs.d.ts.map
  dist/lineup/internal/ScoreUtils.d.ts
  dist/lineup/internal/ScoreUtils.d.ts.map
  dist/vis/sidebar/utils.d.ts
  dist/vis/sidebar/utils.d.ts.map
  src/ATDPApplication.ts
Labels: type: refactor, release: patch
