Repository datavisyn/tdp_core, pull requests merged in 2022-08, with the labels that each got.

#764 Release 15.1.0
  .circleci/config.yml
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  dist/components/buildInfo.d.ts.map
  dist/components/buildInfo.js
  dist/components/buildInfo.js.map
  dist/index.d.ts
  dist/index.d.ts.map
  dist/index.js
  dist/index.js.map
  dist/scss/components/_namedsetlist.scss
  dist/scss/components/_view_lineup.scss
  package.json
  src/components/buildInfo.ts
  src/index.ts
  src/scss/components/_namedsetlist.scss
  src/scss/components/_view_lineup.scss
  tdp_core/security/store/alb_security_store.py
  tdp_core/server/visyn_server.py
  tdp_core/tests/test_main_app.py
  tdp_core/tests/test_security_login.py
Labels: release: minor

#754 Set modal focus based on tour visiblity and replace Bootstrap jQuery modal with plain JS modal
  dist/base/LoginMenu.d.ts
  dist/base/LoginMenu.d.ts.map
  dist/base/LoginMenu.js.map
  dist/base/extensions.d.ts
  dist/base/extensions.d.ts.map
  dist/base/interfaces.d.ts
  dist/base/interfaces.d.ts.map
  dist/base/rest.d.ts
  dist/components/dialogs.d.ts
  dist/components/dialogs.d.ts.map
  dist/components/dialogs.js
  dist/components/dialogs.js.map
  dist/form/FormDialog.d.ts.map
  dist/form/FormDialog.js
  dist/form/FormDialog.js.map
  dist/lineup/Ranking.d.ts
  dist/lineup/Ranking.d.ts.map
  dist/lineup/RankingViewComponent.d.ts
  dist/lineup/RankingViewComponent.d.ts.map
  dist/lineup/panel/PanelDownloadButton.d.ts
  dist/lineup/panel/PanelDownloadButton.d.ts.map
  dist/tour/Tour.d.ts
  dist/tour/Tour.d.ts.map
  dist/tour/TourManager.d.ts
  dist/tour/TourManager.d.ts.map
  dist/tour/TourManager.js
  dist/tour/TourManager.js.map
  dist/tour/TourUtils.d.ts
  dist/tour/TourUtils.d.ts.map
  dist/tour/TourUtils.js
  dist/tour/TourUtils.js.map
  dist/tour/extensions.d.ts
  dist/tour/extensions.d.ts.map
  dist/views/visyn/demo/VisynDemoView.d.ts
  dist/views/visyn/demo/VisynDemoView.d.ts.map
  dist/vis/Vis.d.ts
  dist/vis/Vis.d.ts.map
  dist/vis/VisSidebar.d.ts
  dist/vis/VisSidebar.d.ts.map
  src/base/LoginMenu.ts
  src/base/extensions.ts
  src/base/interfaces.ts
  src/components/dialogs.ts
  src/form/FormDialog.ts
  src/lineup/panel/PanelDownloadButton.ts
  src/tour/Tour.ts
  src/tour/TourManager.ts
  src/tour/TourUtils.ts
  src/tour/extensions.ts
Labels: type: feature, type: refactor, type: technical debt, release: minor

#765 Updated modal typings in dialogs.ts to return HTMLDivElement for body
  dist/components/dialogs.d.ts
  dist/components/dialogs.d.ts.map
  dist/components/dialogs.js.map
  dist/scss/components/_view_lineup.scss
  src/components/dialogs.ts
Labels: type: technical debt, release: minor

#766 Fix Error Where FormDialog Fails to Be Instantiated
  dist/tour/TourUtils.js
  dist/tour/TourUtils.js.map
  src/tour/TourUtils.ts
Labels: type: bug, release: minor

#763 refactor: Avoid general aside styles caused by CLUE
  dist/scss/_clue_override.scss
  src/scss/_clue_override.scss
Labels: type: refactor, release: patch

#767 fix: Font Awesome import in storybook.scss
  dist/scss/storybook.scss
  src/scss/storybook.scss
Labels: type: bug, release: patch

#769 Added d3v7 alias
  package.json
Labels: type: feature, dependencies, release: minor

#770 Override form_check to write print-color-adjust instead of color-adjust
  dist/scss/components/_view.scss
  dist/scss/vendors/bootstrap/_2_components.scss
  dist/scss/vendors/bootstrap/overrides/_form_check.scss
  dist/scss/vendors/bootstrap/overrides/_forms.scss
  src/scss/components/_view.scss
  src/scss/vendors/bootstrap/_2_components.scss
  src/scss/vendors/bootstrap/overrides/_form_check.scss
  src/scss/vendors/bootstrap/overrides/_forms.scss
  workspace.scss
Labels: type: bug, release: minor

#772 fix: Prevent submit of FormDialog with `evt.preventDefault()`
  dist/components/dialogs.d.ts.map
  dist/components/dialogs.js
  dist/components/dialogs.js.map
  src/components/dialogs.ts
Labels: type: bug, priority: high, release: patch

#755 Add structured image column, renderer, and filter dialog for SMILES strings to ranking
  dist/lineup/Ranking.d.ts
  dist/lineup/Ranking.d.ts.map
  dist/lineup/Ranking.js
  dist/lineup/Ranking.js.map
  dist/lineup/desc.d.ts.map
  dist/lineup/desc.js
  dist/lineup/desc.js.map
  dist/lineup/provider/TDPLocalDataProvider.d.ts.map
  dist/lineup/provider/TDPLocalDataProvider.js
  dist/lineup/provider/TDPLocalDataProvider.js.map
  dist/lineup/structureImage/StructureImageColumn.d.ts
  dist/lineup/structureImage/StructureImageColumn.d.ts.map
  dist/lineup/structureImage/StructureImageColumn.js
  dist/lineup/structureImage/StructureImageColumn.js.map
  dist/lineup/structureImage/StructureImageFilterDialog.d.ts
  dist/lineup/structureImage/StructureImageFilterDialog.d.ts.map
  dist/lineup/structureImage/StructureImageFilterDialog.js
  dist/lineup/structureImage/StructureImageFilterDialog.js.map
  dist/lineup/structureImage/StructureImageRenderer.d.ts
  dist/lineup/structureImage/StructureImageRenderer.d.ts.map
  dist/lineup/structureImage/StructureImageRenderer.js
  dist/lineup/structureImage/StructureImageRenderer.js.map
  dist/lineup/structureImage/index.d.ts
  dist/lineup/structureImage/index.d.ts.map
  dist/lineup/structureImage/index.js
  dist/lineup/structureImage/index.js.map
  dist/locales/en/tdp.json
  package.json
  src/lineup/Ranking.tsx
  src/lineup/desc.ts
  src/lineup/provider/TDPLocalDataProvider.ts
  src/lineup/structureImage/StructureImageColumn.ts
  src/lineup/structureImage/StructureImageFilterDialog.ts
  src/lineup/structureImage/StructureImageRenderer.ts
  src/lineup/structureImage/index.ts
  src/locales/en/tdp.json
Labels: type: feature, release: minor

#773 Pin plotly.js-dist-min to 2.12 to avoid selection error
  package.json
Labels: priority: high, dependencies, release: patch

#771 Add test db setup fixture
  requirements.txt
  requirements_dev.txt
  tdp_core/tests/conftest.py
  tdp_core/tests/fixtures/test_db.py
  tdp_core/tests/test_test_db.py
Labels: type: feature, release: minor

#774 Rename test_db to postgres_db
  tdp_core/tests/conftest.py
  tdp_core/tests/fixtures/postgres_db.py
  tdp_core/tests/test_postgres_db.py
Labels: type: refactor, release: patch

#775 Added no security store for static logins
  tdp_core/__init__.py
  tdp_core/security/store/no_security_store.py
  tdp_core/settings/model.py
  tdp_core/tests/test_security_login.py
Labels: type: feature, release: patch
