Repository datavisyn/tdp_core, pull requests merged in 2022-09, with the labels that each got.

#776 Bump rdkit to 2022.3.5
  requirements.txt
  tdp_core/tests/test_rdkit_img.py
Labels: dependencies, release: patch

#780 Release 16.0.1
  .github/workflows/publish.yml
  package.json
Labels: release: patch

#777 Fixing Ranking.tsx bug
  src/lineup/Ranking.tsx
  src/lineup/RankingViewComponent.tsx
Labels: type: bug

#784 Fixed filtering of structure image column
  dist/lineup/structureImage/StructureImageColumn.d.ts
  dist/lineup/structureImage/StructureImageColumn.d.ts.map
  dist/lineup/structureImage/StructureImageColumn.js
  dist/lineup/structureImage/StructureImageColumn.js.map
  dist/lineup/structureImage/StructureImageFilterDialog.js
  dist/lineup/structureImage/StructureImageFilterDialog.js.map
  dist/lineup/structureImage/StructureImageRenderer.js
  dist/lineup/structureImage/StructureImageRenderer.js.map
  src/lineup/structureImage/StructureImageColumn.ts
  src/lineup/structureImage/StructureImageFilterDialog.ts
Labels: type: bug, release: patch

#785 Improve typings for CLUE and refactor async functions
  dist/clue/base/CLUEGraphManager.d.ts
  dist/clue/base/CLUEGraphManager.d.ts.map
  dist/clue/base/CLUEGraphManager.js
  dist/clue/base/CLUEGraphManager.js.map
  dist/clue/graph/GraphBase.d.ts
  dist/clue/graph/GraphBase.d.ts.map
  dist/clue/graph/GraphBase.js
  dist/clue/graph/GraphBase.js.map
  dist/clue/graph/MemoryGraph.d.ts
  dist/clue/graph/MemoryGraph.d.ts.map
  dist/clue/graph/MemoryGraph.js.map
  dist/clue/graph/graph.d.ts
  dist/clue/graph/graph.d.ts.map
  dist/clue/graph/graph.js.map
  dist/clue/provenance/LocalStorageProvenanceGraphManager.d.ts
  dist/clue/provenance/LocalStorageProvenanceGraphManager.d.ts.map
  dist/clue/provenance/LocalStorageProvenanceGraphManager.js.map
  dist/clue/provenance/MixedStorageProvenanceGraphManager.d.ts
  dist/clue/provenance/MixedStorageProvenanceGraphManager.d.ts.map
  dist/clue/provenance/MixedStorageProvenanceGraphManager.js.map
  dist/clue/provenance/ObjectNode.d.ts
  dist/clue/provenance/ProvenanceGraph.d.ts
  dist/clue/provenance/ProvenanceGraph.d.ts.map
  dist/clue/provenance/ProvenanceGraph.js
  dist/clue/provenance/ProvenanceGraph.js.map
  dist/clue/provenance/RemoteStorageProvenanceGraphManager.d.ts
  dist/clue/provenance/RemoteStorageProvenanceGraphManager.d.ts.map
  dist/lineup/Ranking.d.ts.map
  dist/lineup/Ranking.js
  dist/lineup/Ranking.js.map
  dist/lineup/RankingViewComponent.js
  dist/lineup/RankingViewComponent.js.map
  dist/lineup/structureImage/StructureImageColumn.js.map
  dist/utils/TDPApplicationUtils.d.ts
  dist/utils/TDPApplicationUtils.d.ts.map
  dist/utils/TDPApplicationUtils.js.map
  src/clue/base/CLUEGraphManager.ts
  src/clue/graph/GraphBase.ts
  src/clue/graph/MemoryGraph.ts
  src/clue/graph/graph.ts
  src/clue/provenance/LocalStorageProvenanceGraphManager.ts
  src/clue/provenance/MixedStorageProvenanceGraphManager.ts
  src/clue/provenance/ProvenanceGraph.ts
  src/clue/provenance/RemoteStorageProvenanceGraphManager.ts
  src/utils/TDPApplicationUtils.ts
Labels: type: refactor, release: minor

#782 feat: Add datavisyn logo which adapts to the system scheme
  src/assets/icons/datavisyn_logo.svg
  src/assets/icons/datavisyn_logo_blue.svg
Labels: type: feature, release: minor

#794 types: Add `ICategory[]` to `categories` in `IServerColumn`
  src/base/rest.ts
Labels: type: refactor

#796 fix: don't initialize general vis in `ARankingView` when disabled
  dist/lineup/ARankingView.d.ts.map
  dist/lineup/ARankingView.js
  dist/lineup/ARankingView.js.map
  src/lineup/ARankingView.ts
Labels: type: bug, release: minor
