Repository datavisyn/tdp_core, pull requests merged in 2022-03, with the labels that each got.

#653 Add encryptor.py to the security module
  tdp_core/security/utils/__init__.py
  tdp_core/security/utils/encryptor.py
Labels: type: bug, release: patch

#654 Remove 1px border from dark navbar
  dist/scss/components/_header_navbar.scss
  src/scss/components/_header_navbar.scss
Labels: type: bug, release: patch

#666 Ranking component
  dist/lineup/Ranking.d.ts
  dist/lineup/Ranking.d.ts.map
  dist/lineup/Ranking.js
  dist/lineup/Ranking.js.map
  dist/lineup/RankingViewComponent.d.ts
  dist/lineup/RankingViewComponent.d.ts.map
  dist/lineup/RankingViewComponent.js
  dist/lineup/RankingViewComponent.js.map
  dist/lineup/index.d.ts
  dist/lineup/index.d.ts.map
  dist/lineup/index.js
  dist/lineup/index.js.map
  dist/lineup/internal/LineUpSelectionHelper.js
  dist/lineup/internal/LineUpSelectionHelper.js.map
  dist/lineup/panel/PanelAddColumnButton.d.ts.map
  dist/lineup/panel/PanelAddColumnButton.js
  dist/lineup/panel/PanelAddColumnButton.js.map
  dist/views/VisynView.js
  dist/views/VisynView.js.map
  dist/vis/bar/BarVis.d.ts.map
  dist/vis/bar/BarVis.js
  dist/vis/bar/BarVis.js.map
  dist/vis/pcp/PCPVis.d.ts.map
  dist/vis/pcp/PCPVis.js
  dist/vis/pcp/PCPVis.js.map
  dist/vis/scatter/ScatterVis.d.ts.map
  dist/vis/scatter/ScatterVis.js
  dist/vis/scatter/ScatterVis.js.map
  dist/vis/strip/StripVis.d.ts.map
  dist/vis/strip/StripVis.js
  dist/vis/strip/StripVis.js.map
  dist/vis/violin/ViolinVis.d.ts.map
  dist/vis/violin/ViolinVis.js
  dist/vis/violin/ViolinVis.js.map
  src/lineup/Ranking.tsx
  src/lineup/RankingViewComponent.tsx
  src/lineup/index.ts
  src/lineup/internal/LineUpSelectionHelper.ts
  src/lineup/panel/PanelAddColumnButton.ts
  src/vis/bar/BarVis.tsx
  src/vis/pcp/PCPVis.tsx
  src/vis/scatter/ScatterVis.tsx
  src/vis/strip/StripVis.tsx
  src/vis/violin/ViolinVis.tsx
Labels: type: feature, release: minor

#661 Adding Vis Strip Selection
  dist/vis/Vis.d.ts.map
  dist/vis/Vis.js
  dist/vis/Vis.js.map
  dist/vis/interfaces.d.ts
  dist/vis/interfaces.d.ts.map
  dist/vis/interfaces.js
  dist/vis/interfaces.js.map
  dist/vis/strip/StripVis.d.ts
  dist/vis/strip/StripVis.d.ts.map
  dist/vis/strip/StripVis.js
  dist/vis/strip/StripVis.js.map
  dist/vis/strip/utils.d.ts
  dist/vis/strip/utils.d.ts.map
  dist/vis/strip/utils.js
  dist/vis/strip/utils.js.map
  src/vis/Vis.tsx
  src/vis/interfaces.ts
  src/vis/strip/StripVis.tsx
  src/vis/strip/utils.ts
Labels: feature: vis

#664 Scatterplot Pan/Zoom, Multiples improvements
  dist/vis/Vis.d.ts.map
  dist/vis/Vis.js
  dist/vis/Vis.js.map
  dist/vis/VisSidebar.d.ts.map
  dist/vis/VisSidebar.js
  dist/vis/VisSidebar.js.map
  dist/vis/general/layoutUtils.d.ts
  dist/vis/interfaces.d.ts
  dist/vis/interfaces.d.ts.map
  dist/vis/interfaces.js
  dist/vis/interfaces.js.map
  dist/vis/layoutUtils.d.ts.map
  dist/vis/layoutUtils.js
  dist/vis/layoutUtils.js.map
  dist/vis/scatter/ScatterVis.d.ts.map
  dist/vis/scatter/ScatterVis.js
  dist/vis/scatter/ScatterVis.js.map
  dist/vis/scatter/utils.d.ts.map
  dist/vis/scatter/utils.js
  dist/vis/scatter/utils.js.map
  dist/vis/sidebar/BrushOptionButtons.d.ts
  dist/vis/sidebar/BrushOptionButtons.d.ts.map
  dist/vis/sidebar/BrushOptionButtons.js
  dist/vis/sidebar/BrushOptionButtons.js.map
  dist/vis/stories/Iris.stories.d.ts.map
  dist/vis/stories/Iris.stories.js
  dist/vis/stories/Iris.stories.js.map
  dist/vis/stories/Random.stories.d.ts.map
  dist/vis/stories/Random.stories.js
  dist/vis/stories/Random.stories.js.map
  src/vis/Vis.tsx
  src/vis/VisSidebar.tsx
  src/vis/interfaces.ts
  src/vis/layoutUtils.ts
  src/vis/scatter/ScatterVis.tsx
  src/vis/scatter/utils.ts
  src/vis/sidebar/BrushOptionButtons.tsx
  src/vis/stories/Iris.stories.tsx
  src/vis/stories/Random.stories.tsx
Labels: feature: vis
