Repository datavisyn/tdp_core, pull requests merged in 2023-07, with the labels that each got.

#851 Release 20.0.1
  package.json
Labels: release: patch

#850 fix: migrate local to remote graph without intermediate requests
  dist/clue/base/CLUEGraphManager.d.ts
  dist/clue/base/CLUEGraphManager.d.ts.map
  dist/clue/base/CLUEGraphManager.js
  dist/clue/base/CLUEGraphManager.js.map
  dist/clue/graph/GraphProxy.d.ts
  dist/clue/graph/GraphProxy.d.ts.map
  dist/clue/graph/GraphProxy.js
  dist/clue/graph/GraphProxy.js.map
  dist/clue/provenance/MixedStorageProvenanceGraphManager.d.ts
  dist/clue/provenance/ProvenanceGraph.d.ts
  dist/clue/provenance/ProvenanceGraph.d.ts.map
  dist/clue/provenance/ProvenanceGraph.js
  dist/clue/provenance/ProvenanceGraph.js.map
  dist/clue/provenance/RemoteStorageProvenanceGraphManager.d.ts
  dist/clue/provenance/RemoteStorageProvenanceGraphManager.d.ts.map
  dist/clue/provenance/RemoteStorageProvenanceGraphManager.js
  dist/clue/provenance/RemoteStorageProvenanceGraphManager.js.map
  src/clue/base/CLUEGraphManager.ts
  src/clue/graph/GraphBase.ts
  src/clue/graph/GraphProxy.ts
  src/clue/graph/RemoteStorageGraph.ts
  src/clue/provenance/ProvenanceGraph.ts
  src/clue/provenance/RemoteStorageProvenanceGraphManager.ts
Labels: type: bug, release: patch

#852 feat: extend logging in db.py and dbview.py
  requirements_dev.txt
  tdp_core/db.py
  tdp_core/dbview.py
  tdp_core/mapping_table.py
Labels: type: refactor, release: patch

#853 Release 20.1.0
  dist/clue/base/CLUEGraphManager.d.ts
  dist/clue/base/CLUEGraphManager.d.ts.map
  dist/clue/base/CLUEGraphManager.js
  dist/clue/base/CLUEGraphManager.js.map
  dist/clue/graph/GraphBase.d.ts
  dist/clue/graph/GraphBase.d.ts.map
  dist/clue/graph/GraphBase.js.map
  dist/clue/graph/GraphProxy.d.ts
  dist/clue/graph/GraphProxy.d.ts.map
  dist/clue/graph/GraphProxy.js
  dist/clue/graph/GraphProxy.js.map
  dist/clue/graph/RemoteStorageGraph.d.ts
  dist/clue/graph/RemoteStorageGraph.d.ts.map
  dist/clue/graph/RemoteStorageGraph.js
  dist/clue/graph/RemoteStorageGraph.js.map
  dist/clue/provenance/MixedStorageProvenanceGraphManager.d.ts
  dist/clue/provenance/ProvenanceGraph.d.ts
  dist/clue/provenance/ProvenanceGraph.d.ts.map
  dist/clue/provenance/ProvenanceGraph.js
  dist/clue/provenance/ProvenanceGraph.js.map
  dist/clue/provenance/RemoteStorageProvenanceGraphManager.d.ts
  dist/clue/provenance/RemoteStorageProvenanceGraphManager.d.ts.map
  dist/clue/provenance/RemoteStorageProvenanceGraphManager.js
  dist/clue/provenance/RemoteStorageProvenanceGraphManager.js.map
  package.json
  requirements.txt
  requirements_dev.txt
  src/clue/base/CLUEGraphManager.ts
  src/clue/graph/GraphBase.ts
  src/clue/graph/GraphProxy.ts
  src/clue/graph/RemoteStorageGraph.ts
  src/clue/provenance/ProvenanceGraph.ts
  src/clue/provenance/RemoteStorageProvenanceGraphManager.ts
  tdp_core/db.py
  tdp_core/dbview.py
  tdp_core/mapping_table.py
Labels: release: minor
