Repository datavisyn/tdp_core, pull requests merged in 2023-08, with the labels that each got.

#854 deps: remove lineupjs as it is coming from visyn_core
  package.json
Labels: dependencies, release: patch

#855 feat: make SQLAlchemy pool class configurable + add tracer to db.py and dbview.py
  tdp_core/db.py
  tdp_core/dbview.py
Labels: type: feature, release: minor

#856 Release 20.1.1
  package.json
  tdp_core/db.py
  tdp_core/dbview.py
Labels: release: patch

#857 Release 21.0.0
  package.json
  requirements.txt
Labels: release: major
