Repository datavisyn/tdp_core, pull requests merged in 2023-04, with the labels that each got.

#842 feat: make width of step modal dependent on the step count
  dist/scss/components/_tour.scss
  dist/tour/TourManager.d.ts.map
  dist/tour/TourManager.js
  dist/tour/TourManager.js.map
  src/scss/components/_tour.scss
  src/tour/TourManager.ts
Labels: type: feature, release: minor

#843 Release v18.1.0
  dist/base/url/PropertyHandler.d.ts.map
  dist/base/url/PropertyHandler.js
  dist/base/url/PropertyHandler.js.map
  dist/locales/en/tdp.json
  dist/scss/components/_tour.scss
  dist/tour/TourManager.d.ts.map
  dist/tour/TourManager.js
  dist/tour/TourManager.js.map
  package.json
  requirements.txt
  src/base/url/PropertyHandler.ts
  src/locales/en/tdp.json
  src/scss/components/_tour.scss
  src/tour/TourManager.ts
  tdp_core/dataset/dataset_api.py
  tdp_core/sql.py
  tdp_core/storage.py
Labels: release: minor

#844 refactor: migrate clientConfig to Pydantic models
  dist/ATDPApplication.d.ts
  dist/ATDPApplication.d.ts.map
  dist/ATDPApplication.js.map
  src/ATDPApplication.ts
Labels: type: refactor, release: major
