Repository datavisyn/tdp_core, pull requests merged in 2024-02, with the labels that each got.

#871 fix: remove polyfill
  dist/demo/index.template.ejs
  dist/template/_head.html
  src/demo/index.template.ejs
  src/template/_head.html
Labels: dependencies, release: patch

#874 Release 24.0.1
  dist/demo/index.template.ejs
  dist/template/_head.html
  package.json
  requirements.txt
  src/demo/index.template.ejs
  src/template/_head.html
Labels: release: patch

#875 Release 25.0.0
  .storybook/main.js
  .storybook/preview.js
  cypress.config.ts
  dist/scss/abstracts/_variables.scss
  dist/scss/components/_view_lineup.scss
  dist/scss/fontawesome.scss
  dist/scss/main.scss
  dist/scss/storybook.scss
  dist/scss/vendors/_font-awesome.scss
  dist/scss/vendors/_lineup.scss
  dist/scss/vendors/_select2.scss
  dist/scss/vendors/bootstrap/_1_variables_mixins_utilities.scss
  dist/scss/vendors/bootstrap/_2_components.scss
  dist/scss/vendors/bootstrap/overrides/_forms.scss
  package.json
  requirements.txt
  src/scss/abstracts/_variables.scss
  src/scss/components/_view_lineup.scss
  src/scss/fontawesome.scss
  src/scss/main.scss
  src/scss/storybook.scss
  src/scss/vendors/_font-awesome.scss
  src/scss/vendors/_lineup.scss
  src/scss/vendors/_select2.scss
  src/scss/vendors/bootstrap/_1_variables_mixins_utilities.scss
  src/scss/vendors/bootstrap/_2_components.scss
  src/scss/vendors/bootstrap/overrides/_forms.scss
Labels: release: major
